image: bnosac/common

  ## Note that we can only test packages for which we've installed all suggested dependencies; not for all installed packages
script:
  - Rscript --default-packages="stats, graphics, grDevices, datasets, utils, methods, base" -e 'fail <- sapply(c("devtools", "ggplot2", "dplyr", "tidyr", "reshape2", "roxygen2", "knitr", "testthat", "rmarkdown", "httr", "Rcpp"), tools::testInstalledPackage, type=c("examples", "tests"), outDir=tmpdir()); if(any(fail)) stop(fail)'

notify:
  email:
    recipients:
      - jwijffels@bnosac.be



